### ISSUE TITLE
Colloque BigData ULaval

### ISSUE THREAD

**Issue by poivronjaune** [gdgquebec/vr-data-visualisation#5]
Participation au colloque ?

https://www.itis.ulaval.ca/files/content/sites/itis/files/fichiers/Programme_BigData29oct2015.pdf

**Comment by olafleur** [comment]
Malheureusement pas disponible cette journée-là.

Par contre, si vous êtes intéressés, ça serait cool que vous y soyez pour m'en faire un résumé!

**Comment by poivronjaune** [comment]
ADNIA va envoyer quelqu'un d'autre :(
Le 2015-09-22 8:38 AM, "Olivier Lafleur" notifications@github.com a
écrit :
